name : dotnet-sheets-notifications
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build image

  jobs:
  - job: Build
    displayName: Build and push docker image
    steps:
    - task: Docker@2
      displayName: Build the docker image
      inputs:
        command: build
        containerRegistry: dockerHub
        repository: thbst16/azure-function-notification
    - task: Docker@2
      displayName: Push the image to Dockerhub
      inputs:
       command: push
       containerRegistry: dockerHub
       repository: thbst16/azure-function-notification
